name: Release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/cpp
      run: |
        cmake -B build -G "Visual Studio 17 2022"

    - name: Build
      working-directory: ${{github.workspace}}/cpp
      run: |
        cmake --build build --config ${{env.BUILD_CONFIGURATION}}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: |
          ${{github.workspace}}/cpp/build/vscodelua.asi
        body: |
          ## Installation

          - Install [Ultimate-ASI-Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases) to the same directory as your KingdomCome.exe `KingdomComeDeliverance2/Bin/Win64MasterMasterSteamPGO/`
          - Copy the vscodelua.asi file to the same directory

          ## Optional Debug Features
          - Launch the game with `-console` to see debug output in a separate window
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
